# -*- coding: utf-8 -*-
{
    'name': 'Facturación electrónica SII Chile - Núcleo B2B',
    'summary': 'Emisión de DTE B2B (facturas 33/34, notas 56/61 y guías 52) ante el SII.',
    'version': '18.0.2.6.2',
    'description': 'Emisión de DTE B2B ante el SII de Chile. Ver README.md para la documentación completa.',
    'category': 'Accounting/Localizations/EDI',
    'license': 'LGPL-3',
    'author': 'TF',
    'depends': [
        'account',
        'account_edi',
        'stock',
        'sale_stock',
        'contacts',
    ],
    'external_dependencies': {
        # facturacion_electronica (GPLv3+) requiere además pdf417gen, Pillow,
        # pyOpenSSL, zeep, urllib3 y pytz, que se instalan con el paquete.
        'python': ['facturacion_electronica', 'lxml', 'cryptography', 'dateutil'],
    },
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/account_edi_data.xml',
        'data/tf_dte_cl.document_type.csv',
        'data/tf_dte_cl_activity_data.xml',
        'data/tf_dte_cl_cron.xml',
        # Catálogos y certificado antes que los ajustes (sus acciones se usan ahí).
        'views/catalog_views.xml',
        'views/certificate_views.xml',
        'views/caf_views.xml',
        'views/envelope_views.xml',
        'views/res_partner_views.xml',
        'views/res_config_settings_views.xml',
        'views/account_tax_views.xml',
        'views/account_journal_views.xml',
        'views/account_move_views.xml',
        'views/stock_picking_views.xml',
        'views/menuitem.xml',
        'report/report_paperformat.xml',
        'report/report_templates.xml',
        'report/report_actions.xml',
    ],
    'post_init_hook': '_tf_dte_cl_load_comunas',
    'installable': True,
    'application': False,
}
