# -*- coding: utf-8 -*-
{
    'name': 'Facturación electrónica SII Chile - Núcleo B2B',
    'summary': 'Emisión de DTE B2B (Facturas, Notas de Crédito/Débito y Guías de Despacho) '
               'sobre el framework EDI de Odoo.',
    'version': '18.0.1.0.0',
    'category': 'Accounting/Localizations/EDI',
    'license': 'LGPL-3',
    'author': 'TF',
    'depends': [
        'account',
        'account_edi',
        'stock',
        'contacts',
    ],
    'external_dependencies': {
        'python': ['facturacion_electronica', 'pdf417gen', 'lxml', 'PIL', 'OpenSSL', 'dateutil'],
    },
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/account_edi_data.xml',
        'data/tf_dte_cl_cron.xml',
        'data/account_move_docs_sii.csv',
        'views/account_journal_views.xml',
        'views/config_dte_views.xml',
        'views/xml_envio_views.xml',
        'views/account_move_views.xml',
        'views/stock_picking_views.xml',
        'views/res_partner_views.xml',
        'views/res_company_views.xml',
        'views/res_users_views.xml',
        'views/menuitem.xml',
        'report/report_paperformat.xml',
        'report/report_templates.xml',
        'report/report_actions.xml',
    ],
    'installable': True,
    'application': False,
    'post_init_hook': '_cargar_comunas',
}
